### PR TITLE
Completion of work to make xml.js work with emsdk 1.29

### PR DESCRIPTION
**Pull request by sterpe**
Refs #4 

- remove libxml2-2.7.8 tar, update to latest stable libxml2
- add libxml2 as a submodule tracking the official project
- add `--memory-init-file 0` flag which is now different from 3 years ago
- clean up a bit `pre.js` and created `wrapper.js`
- update pre.js to use Module["stdout" /"stderr"] instead of Module["print"]
- Add support for multiple xsd files
- Change the api to support the above.
- Support browser/node/browserify use cases.
- add a package.json to support npm publication.
- update and add tests for in browser/node/browser via browserify.

### CODE REVIEW

**Comment by sterpe** [comment]
Bump.  :)

**Comment by kripken** [comment]
Sorry, I just don't have time for this project these days...

Would you like me to add you as a collaborator on the repo? Assuming you have time for the project :)

**Comment by sterpe** [comment]
Sure.  Thanks!

**Comment by kripken** [comment]
Added. Feel free to merge stuff and everything else.

**Pull request merged**
